# Homework 5, Part 2: Answer questions with pandas

**Use the Excel file to answer the following questions.** This is a little more typical of what your data exploration will look like with pandas.

## 0) Setup

Import pandas **with the correct name** .

In [2]:
import pandas as pd

## 1) Reading in an Excel file

Use pandas to read in the `richpeople.xlsx` Excel file, saving it as a variable with the name we'll always use for a dataframe.

> **TIP:** You will use `read_excel` instead of `read_csv`. Trying `read_excel` the first time will probably not work, you'll get an error message. Be sure to read the error carefully: *you probably need to install a new library before it will work, and the error tells you what the library is named*.

In [3]:
df = pd.read_excel("richpeople.xlsx")
df.head(10)

,year,name,rank,citizenship,countrycode,networthusbillion,selfmade,typeofwealth,gender,age,...,relationshiptocompany,foundingdate,gdpcurrentus,sourceofwealth,notes,notes2,source,source_2,source_3,source_4
0,2014,A. Jerrold Perenchio,663,United States,USA,2.6,self-made,executive,male,83.0,...,former chairman and CEO,1955.0,NaN,"television, Univision",represented Marlon Brando and Elizabeth Taylor,NaN,http://en.wikipedia.org/wiki/Jerry_Perenchio,http://www.forbes.com/profile/a-jerrold-perenc...,COLUMN ONE; A Hollywood Player Who Owns the Ga...,NaN
1,2014,Abdulla Al Futtaim,687,United Arab Emirates,ARE,2.5,inherited,inherited,male,NaN,...,relation,1930.0,NaN,"auto dealers, investments",company split between him and cousin in 2000,NaN,http://en.wikipedia.org/wiki/Al-Futtaim_Group,http://www.al-futtaim.ae/content/groupProfile.asp,NaN,NaN
2,2014,Abdulla bin Ahmad Al Ghurair,305,United Arab Emirates,ARE,4.8,inherited,inherited,male,NaN,...,relation,1960.0,NaN,diversified,inherited from father,NaN,http://en.wikipedia.org/wiki/Al-Ghurair_Group,http://www.alghurair.com/about-us/our-history,NaN,NaN
3,2014,Abdullah Al Rajhi,731,Saudi Arabia,SAU,2.4,self-made,self-made finance,male,NaN,...,founder,1957.0,NaN,banking,NaN,NaN,http://en.wikipedia.org/wiki/Al-Rajhi_Bank,http://www.alrajhibank.com.sa/ar/investor-rela...,http://www.alrajhibank.com.sa/ar/about-us/page...,NaN
4,2014,Abdulsamad Rabiu,1372,Nigeria,NGA,1.2,self-made,founder non-finance,male,54.0,...,founder,1988.0,NaN,"sugar, flour, cement",NaN,NaN,http://www.forbes.com/profile/abdulsamad-rabiu/,http://www.bloomberg.com/research/stocks/priva...,NaN,NaN
5,2014,Abigail Johnson,50,United States,USA,17.3,inherited,inherited,female,52.0,...,relation,1946.0,NaN,money management,3rd generation,no male siblings,"http://en.wikipedia.org/wiki/Edward_Johnson,_III",https://www.fidelity.com/about-fidelity/our-he...,NaN,NaN
6,2014,Abilio dos Santos Diniz,609,Brazil,BRA,2.8,inherited,inherited,male,77.0,...,relation,1948.0,NaN,retail,"kidnapped for 6 days in 1989, inherited from f...",NaN,http://en.wikipedia.org/wiki/Ab%C3%ADlio_Diniz,http://www.forbes.com/profile/abilio-dos-santo...,NaN,NaN
7,2014,Achmad Hamami,1092,Indonesia,IDN,1.6,self-made,founder non-finance,male,83.0,...,founder,1980.0,NaN,heavy equipment,NaN,NaN,http://www.forbes.com/profile/achmad-hamami/,http://www.trakindo.co.id/website/pages/compan...,NaN,NaN
8,2014,Adi Godrej,446,India,IND,3.5,inherited,inherited,male,71.0,...,relation,1897.0,NaN,consumer goods,3rd generation,NaN,http://en.wikipedia.org/wiki/Godrej_family,http://www.forbes.com/profile/godrej/,NaN,NaN
9,2014,Aerin Lauder Zinterhofer,1465,United States,USA,1.1,inherited,inherited,female,44.0,...,relation,1946.0,NaN,"inherited, cosmetics",3rd generation,NaN,http://en.wikipedia.org/wiki/Jane_Lauder,http://investing.businessweek.com/research/sto...,NaN,NaN

## 2) Checking your data

Display the number of rows and columns in your data. Also display the names and data types of each column.

In [4]:
df.describe()

,year,rank,networthusbillion,age,north,politicalconnection,founder,foundingdate,gdpcurrentus
count,1653.0,1653.000000,1653.000000,1590.000000,1653.000000,56.0,1653.000000,1641.000000,0.0
mean,2014.0,809.442226,3.904658,63.342138,0.573503,1.0,0.513612,1963.185253,NaN
std,0.0,463.910597,5.748520,13.137743,0.494718,0.0,0.499966,38.071352,NaN
min,2014.0,1.000000,1.000000,24.000000,0.000000,1.0,0.000000,1615.000000,NaN
25%,2014.0,408.000000,1.400000,53.000000,0.000000,1.0,0.000000,1948.000000,NaN
50%,2014.0,828.000000,2.100000,63.000000,1.000000,1.0,1.000000,1973.000000,NaN
75%,2014.0,1210.000000,3.700000,73.000000,1.000000,1.0,1.000000,1991.000000,NaN
max,2014.0,1565.000000,76.000000,98.000000,1.000000,1.0,1.000000,2012.000000,NaN

In [5]:
df.keys()

Index(['year', 'name', 'rank', 'citizenship', 'countrycode',
       'networthusbillion', 'selfmade', 'typeofwealth', 'gender', 'age',
       'industry', 'IndustryAggregates', 'region', 'north',
       'politicalconnection', 'founder', 'generationofinheritance', 'sector',
       'company', 'companytype', 'relationshiptocompany', 'foundingdate',
       'gdpcurrentus', 'sourceofwealth', 'notes', 'notes2', 'source',
       'source_2', 'source_3', 'source_4'],
      dtype='object')

In [28]:
sorted = df.sort_values(by ="networthusbillion", ascending=False)
sorted.tail()
sorted.tail(50)

,year,name,rank,citizenship,countrycode,networthusbillion,selfmade,typeofwealth,gender,age,...,relationshiptocompany,foundingdate,gdpcurrentus,sourceofwealth,notes,notes2,source,source_2,source_3,source_4
418,2014,Elena Baturina,1565,Russia,RUS,1.0,self-made,privatized and resources,female,50.0,...,founder,1991.0,NaN,construction,former wife mayor of moscow,NaN,http://en.wikipedia.org/wiki/Yelena_Baturina,MOSCOW OVERTAKES NEW YORK AS THE BILLIONAIRES'...,NaN,NaN
766,2014,John Van Lieshout,1565,Australia,AUS,1.0,self-made,self-made finance,male,68.0,...,founder,NaN,NaN,real estate,NaN,NaN,http://www.forbes.com/profile/john-van-lieshout/,"The Courier Mail (Australia) July 25, 2015 Sat...",NaN,NaN
1350,2014,Sergei Petrov,1565,Russia,RUS,1.0,self-made,founder non-finance,male,59.0,...,founder,1990.0,NaN,auto import and dealerships,NaN,NaN,http://www.forbes.com/profile/sergei-petrov/,Far Eastern City Sees Kremlin as Cause of Its ...,NaN,NaN
759,2014,John Morgridge,1565,United States,USA,1.0,self-made,executive,male,80.0,...,ceo,1984.0,NaN,Cisco,NaN,NaN,A hiring that changed the course of networking...,http://en.wikipedia.org/wiki/Cisco_Systems,http://www.forbes.com/profile/john-morgridge/,NaN
1061,2014,Mikhail Abyzov,1565,Russia,RUS,1.0,self-made,privatized and resources,male,41.0,...,Chairman,2006.0,NaN,"power, power engineering",NaN,NaN,http://en.wikipedia.org/wiki/Mikhail_Abyzov,http://www.forbes.com/profile/mikhail-abyzov/,Blow to British coal as Powerfuel hits rocks T...,NaN
1445,2014,T.S. Kalyanaraman,1565,India,IND,1.0,self-made,founder non-finance,male,66.0,...,founder,1993.0,NaN,jewelry,NaN,NaN,http://en.wikipedia.org/wiki/T.S._Kalyanaraman,http://www.bloomberg.com/news/articles/2013-01...,NaN,NaN
276,2014,Christopher Burch,1565,United States,USA,1.0,self-made,founder non-finance,male,60.0,...,founder,2004.0,NaN,fashion,NaN,NaN,http://en.wikipedia.org/wiki/J._Christopher_Burch,http://www.forbes.com/profile/christopher-burch/,http://www.vanityfair.com/news/2007/02/tory-bu...,NaN
603,2014,Horst Julius Pudwill,1565,Germany,DEU,1.0,self-made,founder non-finance,male,69.0,...,founder,1985.0,NaN,manufacturing,NaN,NaN,http://www.forbes.com/profile/horst-julius-pud...,NaN,NaN,NaN
121,2014,Anne Beaufour,1565,France,FRA,1.0,inherited,inherited,female,50.0,...,relation,1929.0,NaN,pharmaceuticals,3rd generation,NaN,http://en.wikipedia.org/wiki/Ipsen,http://www.ipsen.com/le-groupe/historique-du-g...,http://www.forbes.com/profile/anne-beaufour/,NaN
476,2014,Fred Chang,1565,United States,USA,1.0,self-made,founder non-finance,male,57.0,...,founder,2001.0,NaN,online retailing,NaN,NaN,http://en.wikipedia.org/wiki/Newegg,http://www.newegg.com/Info/FactSheet.aspx,http://www.forbes.com/sites/andreanavarro/2014...,NaN
1190,2014,Philip Falcone,1565,United States,USA,1.0,self-made,self-made finance,male,51.0,...,founder,2001.0,NaN,hedge funds,NaN,NaN,http://en.wikipedia.org/wiki/Philip_Falcone,FROM IRON RANGE HOCKEY HERO TO WALL STREET STA...,NaN,NaN
224,2014,Carlos Martins,1565,Brazil,BRA,1.0,self-made,founder non-finance,male,57.0,...,founder,1987.0,NaN,education,NaN,NaN,http://en.wikipedia.org/wiki/Carlos_Roberto_Ma...,http://www.mh1.com.br/english/courses.asp,NaN,NaN
1529,2014,Vivek Chaand Sehgal,1565,Australia,AUS,1.0,self-made,founder non-finance,male,57.0,...,founder,1986.0,NaN,auto parts,"Indian founder of Motherson Sumi, Australian c...",NaN,http://www.forbes.com/profile/vivek-chaand-seh...,http://en.wikipedia.org/wiki/Motherson_Sumi_Sy...,NaN,Will Vivek Sehgalâ€™s Gambit Pay Off? Rashmi K...
723,2014,Jim Thompson,1565,United States,USA,1.0,self-made,founder non-finance,male,74.0,...,founder,1965.0,NaN,logistics,NaN,NaN,http://en.wikipedia.org/wiki/James_E._Thompson,http://en.wikipedia.org/wiki/Crown_Worldwide_G...,http://www.forbes.com/profile/jim-thompson/,NaN
1095,2014,Murat Vargi,1565,Turkey,TUR,1.0,self-made,founder non-finance,male,66.0,...,founder,1993.0,NaN,telecom,NaN,NaN,http://www.forbes.com/profile/murat-vargi/,http://en.wikipedia.org/wiki/Turkcell,http://www.bloomberg.com/research/stocks/priva...,NaN
191,2014,Boris Mints,1565,Russia,RUS,1.0,self-made,self-made finance,male,55.0,...,owner,2010.0,NaN,real estate,NaN,NaN,http://www.forbes.com/profile/boris-mints/,http://www.o1properties.ru/o1properties/about-...,http://www.bloomberg.com/research/stocks/priva...,NaN
1042,2014,Michael Lynch,1565,United Kingdom,GBR,1.0,self-made,founder non-finance,male,49.0,...,founder,1996.0,NaN,software,NaN,NaN,http://en.wikipedia.org/wiki/Michael_Richard_L...,http://www.theguardian.com/business/2011/aug/1...,NaN,NaN
1585,2014,"William Moncrief, Jr.",1565,United States,USA,1.0,inherited,inherited,male,93.0,...,relation,1929.0,NaN,oil,joined father's business following WWII,NaN,http://en.wikipedia.org/wiki/William_Moncrief,http://www.moncriefoil.com/history.htm,NaN,NaN
115,2014,Angela Bennett,1565,Australia,AUS,1.0,inherited,inherited,female,69.0,...,relation,1955.0,NaN,mining,inherited from father,shared fortune with brother,http://www.forbes.com/profile/angela-bennett/,NaN,NaN,NaN
1089,2014,Morris Kahn,1565,Israel,ISR,1.0,self-made,executive,male,84.0,...,investor,1982.0,NaN,software,NaN,NaN,http://www.forbes.com/profile/morris-kahn/,http://en.wikipedia.org/wiki/Amdocs,http://www.haaretz.com/israel-news/confessions...,NaN
920,2014,Lim Hariyanto Wijaya Sarwono,1565,Indonesia,IDN,1.0,self-made,privatized and resources,male,86.0,...,founder,1996.0,NaN,palm oil,NaN,NaN,http://www.forbes.com/profile/lim-hariyanto-wi...,http://en.wikipedia.org/wiki/Bumitama_Agri,NaN,NaN
1086,2014,Monika Schoeller,1565,Germany,DEU,1.0,inherited,inherited,female,75.0,...,relation,1948.0,NaN,publishing,inherited from father,NaN,http://www.forbes.com/profile/monika-schoeller/,NaN,NaN,NaN
111,2014,Andrew Gotianun,1565,Philippines,PHL,1.0,self-made,self-made finance,male,86.0,...,founder,1955.0,NaN,real estate,NaN,NaN,http://en.wikipedia.org/wiki/Andrew_Gotianun,http://www.forbes.com/profile/andrew-gotianun/,Second-hand car dealer discovers road to riche...,NaN
156,2014,B.R. Shetty,1565,India,IND,1.0,self-made,founder non-finance,male,72.0,...,founder,1975.0,NaN,healthcare,NaN,NaN,http://en.wikipedia.org/wiki/B._R._Shetty,http://www.nmchealth.com/dr-br-shetty/,NaN,NaN
82,2014,An Kang,1565,China,CHN,1.0,self-made,founder non-finance,male,65.0,...,founder,1992.0,NaN,pharmaceuticals,NaN,NaN,http://www.forbes.com/profile/an-kang/,http://english.hualanbio.com/enterhualan/history/,NaN,NaN
1310,2014,Rostam Azizi,1565,Tanzania,TZA,1.0,self-made,executive,male,49.0,...,investor,1999.0,NaN,"telecom, investments",NaN,NaN,http://www.forbes.com/profile/rostam-azizi/,http://en.wikipedia.org/wiki/Vodacom_Tanzania,http://www.thecitizen.co.tz/News/Rostam--Dewji...,NaN
1497,2014,Tory Burch,1565,United States,USA,1.0,self-made,founder non-finance,female,47.0,...,founder,2004.0,NaN,fashion,NaN,NaN,http://en.wikipedia.org/wiki/J._Christopher_Burch,http://www.vanityfair.com/news/2007/02/tory-bu...,NaN,NaN
209,2014,C. James Koch,1565,United States,USA,1.0,self-made,founder non-finance,male,64.0,...,founder,1984.0,NaN,beer,NaN,NaN,http://en.wikipedia.org/wiki/Samuel_Adams_(beer),SAM ADAMS CREATOR THRIVES AMID CRAFT BEER SURG...,NaN,NaN
371,2014,Ding Shizhong,1565,China,CHN,1.0,self-made,executive,male,43.0,...,director,1966.0,NaN,retail,NaN,NaN,http://www.sce-re.com/en/about.asp,http://www.forbes.com/profile/ding-shizhong/,NaN,NaN
923,2014,Lin Ming-Hsiung,1565,Taiwan,Taiwan,1.0,self-made,privatized and resources,male,64.0,...,owner,1998.0,NaN,retail,NaN,NaN,http://www.forbes.com/profile/lin-ming-hsiung/,http://www.taipeitimes.com/News/taiwan/archive...,NaN,NaN
485,2014,Fu Kwan,1565,China,CHN,1.0,self-made,self-made finance,male,56.0,...,chairman,1990.0,NaN,diversified,NaN,NaN,http://www.forbes.com/profile/fu-kwan/,http://www.macrolink.com.cn/en/AboutBig.aspx,NaN,NaN
376,2014,Dmitry Korzhev,1565,Russia,RUS,1.0,self-made,founder non-finance,male,50.0,...,founder,1993.0,NaN,retail,NaN,NaN,http://www.forbes.com/profile/dmitry-korzhev/,http://www.bloomberg.com/profiles/people/16388...,NaN,NaN
727,2014,Jitendra Virwani,1565,India,IND,1.0,self-made,self-made finance,male,48.0,...,founder,1993.0,NaN,real estate,NaN,NaN,http://www.forbes.com/profile/jitendra-virwani/,NaN,NaN,NaN
380,2014,Dmitry Troitsky,1565,Russia,RUS,1.0,self-made,founder non-finance,male,49.0,...,founder,1993.0,NaN,retail,NaN,NaN,http://www.forbes.com/profile/dmitry-troitsky/,NaN,NaN,NaN
1609,2014,Yang Keng,1565,China,CHN,1.0,self-made,self-made finance,male,53.0,...,chairman,NaN,NaN,real estate,NaN,NaN,http://www.forbes.com/profile/yang-keng/,NaN,NaN,NaN
195,2014,Brian Higgins,1565,United States,USA,1.0,self-made,self-made finance,male,49.0,...,founder,1995.0,NaN,Hedge fund,NaN,NaN,http://www.forbes.com/profile/brian-higgins-1/,http://www.forbes.com/sites/nathanvardi/2014/0...,NaN,NaN
698,2014,Jeanine Dick,1565,France,FRA,1.0,inherited,inherited,female,77.0,...,relation,1968.0,NaN,animal pharmaceuticals,widow,NaN,http://www.forbes.com/profile/jeanine-dick/,NaN,NaN,NaN
1398,2014,Stefan von Holtzbrinck,1565,Germany,DEU,1.0,inherited,inherited,male,50.0,...,relation,1948.0,NaN,publishing,inherited from father,NaN,http://www.forbes.com/profile/monika-schoeller/,NaN,NaN,NaN
1336,2014,Sara Blakely,1565,United States,USA,1.0,self-made,founder non-finance,female,43.0,...,founder,2000.0,NaN,Spanx,NaN,NaN,http://en.wikipedia.org/wiki/Spanx,http://www.wsj.com/articles/a-day-in-the-life-...,NaN,NaN
636,2014,Ina Chan,1565,Hong Kong,HKG,1.0,inherited,inherited,female,60.0,...,relation,1962.0,NaN,casinos,3rd wife,NaN,http://www.forbes.com/profile/ina-chan/,NaN,NaN,NaN
936,2014,Liu Xiaomeng,1565,China,CHN,1.0,self-made,executive,female,59.0,...,investor,1990.0,NaN,appliance retailer,NaN,NaN,http://www.forbes.com/profile/liu-xiaomeng/,NaN,NaN,NaN
567,2014,Harindarpal Banga,1565,India,IND,1.0,self-made,privatized and resources,male,63.0,...,Vice Chairman,1986.0,NaN,commodities,NaN,NaN,http://en.wikipedia.org/wiki/Noble_Group_Limited,http://www.forbes.com/profile/harindarpal-banga/,NaN,NaN
456,2014,Feng Hailiang,1565,China,CHN,1.0,self-made,founder non-finance,male,53.0,...,founder,1989.0,NaN,copper processing & real estate,NaN,NaN,http://www.forbes.com/profile/feng-hailiang/,http://www.hailiang.com/en/about_int.php,NaN,NaN
539,2014,Graham Kirkham,1565,United Kingdom,GBR,1.0,self-made,founder non-finance,male,69.0,...,founder,1983.0,NaN,furniture retail,NaN,NaN,"http://en.wikipedia.org/wiki/Graham_Kirkham,_B...",http://www.forbes.com/profile/graham-kirkham/,http://www.independent.co.uk/news/business/kir...,NaN
891,2014,Leon Charney,1565,United States,USA,1.0,self-made,self-made finance,male,72.0,...,investor,1980.0,NaN,real estate,NaN,NaN,http://www.forbes.com/profile/leon-charney/,Is Now the Right Time for a National Washingto...,NaN,NaN
1598,2014,Wu Xiong,1565,China,CHN,1.0,self-made,executive,male,NaN,...,owner,1999.0,NaN,infant formula,NaN,NaN,http://www.forbes.com/profile/wu-xiong/,NaN,NaN,NaN
1554,2014,Wang Muqing,1565,China,CHN,1.0,self-made,founder non-finance,male,63.0,...,founder,1999.0,NaN,auto distribution,NaN,NaN,http://www.forbes.com/profile/wang-muqing/,http://www.zhengtongauto.com/en/milestone.html,NaN,NaN
1596,2014,Wu Chung-Yi,1565,Taiwan,Taiwan,1.0,self-made,executive,male,55.0,...,investor,1991.0,NaN,manufacturing,NaN,NaN,http://www.forbes.com/profile/wu-chung-yi/,http://en.wikipedia.org/wiki/Tingyi_(Cayman_Is...,Tingyi-Campbell sale talks stay on track South...,NaN
904,2014,Li Denghai,1565,China,CHN,1.0,self-made,founder non-finance,male,64.0,...,founder,1989.0,NaN,agribusiness,NaN,NaN,http://www.forbes.com/profile/li-denghai/,NaN,NaN,NaN
370,2014,Ding Shijia,1565,China,CHN,1.0,self-made,executive,male,50.0,...,deputy chairman,1994.0,NaN,shoes,NaN,NaN,http://en.wikipedia.org/wiki/Anta_Sports,http://en.wikipedia.org/wiki/Ding_Shijia,http://www.bloomberg.com/research/stocks/peopl...,NaN

## 3) Who are the top 10 richest billionaires? Use the `networthusbillion` column.

In [6]:
# nw = df.groupby(by ="networthusbillion")
# nw.sort_values("networthusbillion", ascending=False)
df.sort_values("networthusbillion", ascending=False).head(10)

,year,name,rank,citizenship,countrycode,networthusbillion,selfmade,typeofwealth,gender,age,...,relationshiptocompany,foundingdate,gdpcurrentus,sourceofwealth,notes,notes2,source,source_2,source_3,source_4
184,2014,Bill Gates,1,United States,USA,76.0,self-made,founder non-finance,male,58.0,...,founder,1975.0,NaN,Microsoft,NaN,NaN,http://www.forbes.com/profile/bill-gates/,NaN,NaN,NaN
226,2014,Carlos Slim Helu,2,Mexico,MEX,72.0,self-made,privatized and resources,male,74.0,...,founder,1990.0,NaN,telecom,NaN,NaN,http://www.ozy.com/provocateurs/carlos-slims-w...,NaN,NaN,NaN
79,2014,Amancio Ortega,3,Spain,ESP,64.0,self-made,founder non-finance,male,77.0,...,founder,1975.0,NaN,retail,NaN,NaN,http://www.forbes.com/profile/amancio-ortega/,NaN,NaN,NaN
1562,2014,Warren Buffett,4,United States,USA,58.2,self-made,founder non-finance,male,83.0,...,founder,1839.0,NaN,Berkshire Hathaway,NaN,NaN,http://www.forbes.com/lists/2009/10/billionair...,http://www.forbes.com/companies/berkshire-hath...,NaN,NaN
862,2014,Larry Ellison,5,United States,USA,48.0,self-made,founder non-finance,male,69.0,...,founder,1977.0,NaN,Oracle,NaN,NaN,http://www.forbes.com/profile/larry-ellison/,http://www.businessinsider.com/how-larry-ellis...,NaN,NaN
339,2014,David Koch,6,United States,USA,40.0,inherited,inherited,male,73.0,...,relation,1940.0,NaN,diversified,inherited from father,NaN,http://www.kochind.com/About_Koch/History_Time...,NaN,NaN,NaN
247,2014,Charles Koch,6,United States,USA,40.0,inherited,inherited,male,78.0,...,relation,1940.0,NaN,diversified,inherited from father,NaN,http://www.kochind.com/About_Koch/History_Time...,NaN,NaN,NaN
1364,2014,Sheldon Adelson,8,United States,USA,38.0,self-made,self-made finance,male,80.0,...,founder,1952.0,NaN,casinos,NaN,NaN,http://www.forbes.com/profile/sheldon-adelson/,http://lasvegassun.com/news/1996/nov/26/rat-pa...,NaN,NaN
280,2014,Christy Walton,9,United States,USA,36.7,inherited,inherited,female,59.0,...,relation,1962.0,NaN,Wal-Mart,widow,NaN,http://www.forbes.com/profile/christy-walton/,NaN,NaN,NaN
724,2014,Jim Walton,10,United States,USA,34.7,inherited,inherited,male,66.0,...,relation,1962.0,NaN,Wal-Mart,inherited from father,NaN,http://www.forbes.com/profile/jim-walton/,NaN,NaN,NaN

In [20]:
df.tail()

,year,name,rank,citizenship,countrycode,networthusbillion,selfmade,typeofwealth,gender,age,...,relationshiptocompany,foundingdate,gdpcurrentus,sourceofwealth,notes,notes2,source,source_2,source_3,source_4
1648,2014,Zhu Yicai,1154,China,CHN,1.5,self-made,self-made finance,male,49.0,...,founder,1993.0,NaN,diversified,NaN,NaN,http://www.forbes.com/profile/zhu-yicai/,NaN,NaN,NaN
1649,2014,Ziyad Manasir,609,Russia,RUS,2.8,self-made,privatized and resources,male,48.0,...,founder,1992.0,NaN,construction,close ties with Gazprom,NaN,http://www.forbes.com/profile/ziyad-manasir/,http://www.themoscowtimes.com/business/article...,NaN,NaN
1650,2014,Ziyaudin Magomedov,1372,Russia,RUS,1.2,self-made,privatized and resources,male,45.0,...,founder,2004.0,NaN,"port, gas",NaN,NaN,http://www.summagroup.ru/about/history/en/,http://www.forbes.com/profile/ziyaudin-magomedov/,NaN,NaN
1651,2014,Zong Qinghou,94,China,CHN,11.6,self-made,founder non-finance,male,68.0,...,founder,1987.0,NaN,beverages,NaN,NaN,http://en.wikipedia.org/wiki/Zong_Qinghou,http://mic.com/articles/39659/zong-qinghou-chi...,NaN,NaN
1652,2014,Zygmunt Solorz-Zak,446,Poland,POL,3.5,self-made,founder non-finance,male,57.0,...,founder,1992.0,NaN,TV broadcasting,NaN,NaN,http://en.wikipedia.org/wiki/Zygmunt_Solorz-%C...,No Mob Bosses in This Legal Strategy The New Y...,NaN,NaN

## 4a) How many male billionaires are there compared to the number of female billionares?

> **TIP:** The last part uses `groupby`, but the count/percent part does not.
> **TIP:** When I say "average," you can pick what kind of average you use.

In [9]:
#create subgroup of men
male = df[df.gender == "male"]
len(male)

1473

In [8]:
#create subgroup of women
fem = df[df.gender == "female"]
len(fem)

180

## 4b) What percent is that?

In [18]:
len(male)/len(fem)
ratio = len(male)/len(fem)
ratio = round(ratio,1)
ratio

8.2

## 4c) Is the average wealth different for a female billionaire as compared to a male billionaire?

In [19]:
malemed = male.networthusbillion.median()
malemed

2.1

In [21]:
malemean = male.networthusbillion.mean()
malemean

3.902715546503741

In [23]:
femmean = fem.networthusbillion.mean()
femmean

3.9205555555555565

In [24]:
femmed = fem.networthusbillion.median()
femmed

2.3

In [31]:
femmean > malemean

True

In [32]:
femmed > malemed

True

## 5a) What is the most common source/type of wealth?

In [34]:
#PATTERN: df.sort_values(by ="length", ascending=False)
df.sort_values(by = "typeofwealth", ascending=False)

,year,name,rank,citizenship,countrycode,networthusbillion,selfmade,typeofwealth,gender,age,...,relationshiptocompany,foundingdate,gdpcurrentus,sourceofwealth,notes,notes2,source,source_2,source_3,source_4
825,2014,Ken Fisher,731,United States,USA,2.4,self-made,self-made finance,male,63.0,...,founder,1979.0,NaN,Money management,NaN,NaN,http://en.wikipedia.org/wiki/Kenneth_Fisher,http://www.forbes.com/profile/ken-fisher/,http://www.investmentnews.com/article/20150414...,NaN
610,2014,Huang Rulun,609,China,CHN,2.8,self-made,self-made finance,male,62.0,...,founder,1991.0,NaN,real estate,NaN,NaN,http://www.forbes.com/profile/huang-rulun/,http://investing.businessweek.com/research/sto...,NaN,NaN
597,2014,Herbert Simon,868,United States,USA,2.1,self-made,self-made finance,male,79.0,...,founder,1960.0,NaN,real estate,NaN,NaN,http://en.wikipedia.org/wiki/Herbert_Simon_(re...,http://en.wikipedia.org/wiki/Simon_Property_Group,http://www.nytimes.com/2009/09/18/business/18s...,NaN
1432,2014,Sun Hongbin,1540,United States,USA,1.1,self-made,self-made finance,male,51.0,...,founder,1994.0,NaN,real estate,NaN,NaN,http://www.sunac.com.cn/en/NewsList_40.aspx,From jailbird to billionaire; Sun Hongbin rose...,NaN,NaN
1431,2014,Sun Guangxin,466,China,CHN,3.4,self-made,self-made finance,male,51.0,...,founder,1989.0,NaN,diversified,investment in energy in Xinjiang/Kazakhstan,NaN,http://www.guanghui.com/Typ.aspx?id=020102&Typ...,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
401,2014,Edmund Ansin,1210,United States,USA,1.4,self-made,executive,male,77.0,...,chairman,1962.0,NaN,television,NaN,NaN,http://en.wikipedia.org/wiki/Sunbeam_Television,TV EXECUTIVE WEATHERS CONTROVERSY IN BOSTON Th...,NaN,NaN
400,2014,Edir Macedo,1465,Brazil,BRA,1.1,self-made,executive,male,69.0,...,owner,1953.0,NaN,broadcasting,NaN,NaN,http://en.wikipedia.org/wiki/Edir_Macedo,http://www.forbes.com/profile/edir-macedo/,NaN,NaN
0,2014,A. Jerrold Perenchio,663,United States,USA,2.6,self-made,executive,male,83.0,...,former chairman and CEO,1955.0,NaN,"television, Univision",represented Marlon Brando and Elizabeth Taylor,NaN,http://en.wikipedia.org/wiki/Jerry_Perenchio,http://www.forbes.com/profile/a-jerrold-perenc...,COLUMN ONE; A Hollywood Player Who Owns the Ga...,NaN
1081,2014,Mohammed Al Issa,520,Saudi Arabia,SAU,3.1,NaN,NaN,male,89.0,...,shareholder,1979.0,NaN,investments,NaN,NaN,http://www.forbes.com/profile/mohammed-al-issa/,http://www.savola.com/SavolaE/Board_of_Directo...,NaN,NaN
1332,2014,Samuel Yin,483,Taiwan,Taiwan,3.3,NaN,NaN,male,63.0,...,NaN,NaN,NaN,diversified,NaN,NaN,http://www.forbes.com/profile/samuel-yin/,Sinopec eyes spin-off from Ruentex pact; Agree...,NaN,NaN

In [35]:
#data['column_name'].value_counts()[value]
df["typeofwealth"].value_counts()["self-made finance"]

344

In [36]:
df["typeofwealth"].value_counts()["executive"]

142

## 5b) Is the most common source/type of wealth different between men and women?

> **TIP:** You know how to `groupby` and you know how to count how many times a value is in a column. Can you put them together???
>
> **TIP:** Use percentages for this, it makes it a lot more readable.

In [39]:
femsource = fem.sort_values(by = "typeofwealth", ascending=False)
femsource

,year,name,rank,citizenship,countrycode,networthusbillion,selfmade,typeofwealth,gender,age,...,relationshiptocompany,foundingdate,gdpcurrentus,sourceofwealth,notes,notes2,source,source_2,source_3,source_4
1638,2014,Zhang Xin,408,China,CHN,3.7,self-made,self-made finance,female,48.0,...,founder,1995.0,NaN,real estate,NaN,NaN,http://en.wikipedia.org/wiki/Zhang_Xin_(busine...,NaN,NaN,NaN
1603,2014,Xiu Li Hawken,1372,United Kingdom,GBR,1.2,self-made,self-made finance,female,51.0,...,owner,2007.0,NaN,real estate,NaN,NaN,http://www.forbes.com/profile/xiu-li-hawken/,http://investing.businessweek.com/research/sto...,NaN,NaN
1203,2014,Pollyanna Chu,1092,Hong Kong,HKG,1.6,self-made,self-made finance,female,56.0,...,founder,1992.0,NaN,financial services,NaN,NaN,http://en.wikipedia.org/wiki/Pollyanna_Chu,NaN,NaN,NaN
232,2014,Chan Laiwa,234,China,CHN,6.0,self-made,self-made finance,female,73.0,...,founder,1988.0,NaN,real estate,NaN,NaN,http://en.wikipedia.org/wiki/Chan_Laiwa,http://www.fuwahgroup.com/index.php?option=com...,NaN,NaN
859,2014,Lam Fong Ngo,1565,Macau,MAC,1.0,self-made,self-made finance,female,NaN,...,Vice Chairman,1997.0,NaN,casinos,NaN,NaN,http://www.forbes.com/profile/david-chow-1/,http://www.macaulegend.com/html/about_mileston...,Macau Legend to roll the dice on HK IPO; But l...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1368,2014,Sheryl Sandberg,1540,United States,USA,1.1,self-made,executive,female,44.0,...,COO,2004.0,NaN,Facebook,NaN,NaN,http://en.wikipedia.org/wiki/Sheryl_Sandberg,http://www.newyorker.com/magazine/2011/07/11/a...,NaN,NaN
1552,2014,Wang Laichun,1540,China,CHN,1.1,self-made,executive,female,46.0,...,chairwomen,2004.0,NaN,electronics components,NaN,NaN,http://www.forbes.com/profile/wang-laichun/,http://web.luxshare-ict.com/en/AboutLuxshare-I...,NaN,NaN
960,2014,Lynda Resnick,1036,United States,USA,1.8,self-made,executive,female,NaN,...,owner,1934.0,NaN,NaN,Purchased in 1979,NaN,http://en.wikipedia.org/wiki/Lynda_Resnick,http://www.forbes.com/profile/stewart-and-lynd...,http://www.teleflora.com/info/about,NaN
936,2014,Liu Xiaomeng,1565,China,CHN,1.0,self-made,executive,female,59.0,...,investor,1990.0,NaN,appliance retailer,NaN,NaN,http://www.forbes.com/profile/liu-xiaomeng/,NaN,NaN,NaN
295,2014,Cristina Green,663,United Kingdom,GBR,2.6,self-made,executive,female,NaN,...,owner,1903.0,NaN,NaN,NaN,NaN,http://en.wikipedia.org/wiki/Arcadia_Group,http://www.forbes.com/profile/philip-cristina-...,NaN,NaN

In [40]:
malesource = male.sort_values(by = "typeofwealth", ascending=False)
malesource

,year,name,rank,citizenship,countrycode,networthusbillion,selfmade,typeofwealth,gender,age,...,relationshiptocompany,foundingdate,gdpcurrentus,sourceofwealth,notes,notes2,source,source_2,source_3,source_4
828,2014,Kenneth Langone,764,United States,USA,2.3,self-made,self-made finance,male,78.0,...,founder,1979.0,NaN,investments,NaN,NaN,http://en.wikipedia.org/wiki/Bernard_Marcus,https://corporate.homedepot.com/OurCompany/His...,ANGRY BIZ MOGUL 'SPITZ' ON ELIOT The New York ...,NaN
597,2014,Herbert Simon,868,United States,USA,2.1,self-made,self-made finance,male,79.0,...,founder,1960.0,NaN,real estate,NaN,NaN,http://en.wikipedia.org/wiki/Herbert_Simon_(re...,http://en.wikipedia.org/wiki/Simon_Property_Group,http://www.nytimes.com/2009/09/18/business/18s...,NaN
622,2014,Hui Wing Mau,244,Hong Kong,HKG,5.7,self-made,self-made finance,male,63.0,...,founder,1988.0,NaN,real estate,(aka Xu Rongmao) claimed to invest in a knitti...,NaN,http://en.wikipedia.org/wiki/Xu_Rongmao,http://www.smh.com.au/business/the-selfmade-au...,NaN,NaN
1411,2014,Stephen Schwarzman,122,United States,USA,10.0,self-made,self-made finance,male,67.0,...,founder,1985.0,NaN,private equity,NaN,NaN,http://en.wikipedia.org/wiki/Stephen_A._Schwar...,https://www.blackstone.com/the-firm/overview/h...,http://www.nytimes.com/2015/09/06/business/dea...,NaN
620,2014,Hui Ka Yan,244,China,CHN,5.7,self-made,self-made finance,male,55.0,...,chairman,1997.0,NaN,real estate,NaN,NaN,http://www.evergrande.com/en/about.aspx?uc=course,http://www.forbes.com/profile/hui-ka-yan/,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1505,2014,Tu Jianhua,1372,China,CHN,1.2,self-made,executive,male,50.0,...,chairman,NaN,NaN,"motorcycles, real estate",NaN,NaN,http://www.forbes.com/profile/tu-jianhua/,NaN,NaN,NaN
1274,2014,Robert Ingham,1565,Australia,AUS,1.0,self-made,executive,male,82.0,...,relation,1918.0,NaN,agribusiness,inherited family farm and turned it into poutr...,NaN,http://www.forbes.com/profile/robert-ingham/,http://en.wikipedia.org/wiki/Inghams_Enterprises,NaN,NaN
0,2014,A. Jerrold Perenchio,663,United States,USA,2.6,self-made,executive,male,83.0,...,former chairman and CEO,1955.0,NaN,"television, Univision",represented Marlon Brando and Elizabeth Taylor,NaN,http://en.wikipedia.org/wiki/Jerry_Perenchio,http://www.forbes.com/profile/a-jerrold-perenc...,COLUMN ONE; A Hollywood Player Who Owns the Ga...,NaN
1081,2014,Mohammed Al Issa,520,Saudi Arabia,SAU,3.1,NaN,NaN,male,89.0,...,shareholder,1979.0,NaN,investments,NaN,NaN,http://www.forbes.com/profile/mohammed-al-issa/,http://www.savola.com/SavolaE/Board_of_Directo...,NaN,NaN
1332,2014,Samuel Yin,483,Taiwan,Taiwan,3.3,NaN,NaN,male,63.0,...,NaN,NaN,NaN,diversified,NaN,NaN,http://www.forbes.com/profile/samuel-yin/,Sinopec eyes spin-off from Ruentex pact; Agree...,NaN,NaN

## 6) What companies have the most billionaires? Graph the top 5 as a horizontal bar graph.

> **TIP:** First find the answer to the question, then just try to throw `.plot()` on the end
>
> **TIP:** You can use `.head()` on *anything*, not just your basic `df`
>
> **TIP:** You might feel like you should use `groupby`, but don't! There's an easier way to count.
>
> **TIP:** Make the largest bar be at the top of the graph
>
> **TIP:** If your chart seems... weird, think about where in the process you're sorting vs using `head`

## 7) How much money do these top 5 billionaires have in total?

## 8) What are the top 10 countries with the most money held by billionaires?

I am **not** asking which country has the most billionaires - this is **total amount of money per country.**

> **TIP:** Think about it in steps - "I want them organized by country," "I want their net worth," "I want to add it all up," and "I want 10 of them." Just chain it all together.

## 9a) How old is an average billionaire?

## 9b) How old are self-made billionaires compared to non self-made billionaires?

## 10a) Who are the three youngest billionaires? Who are the three oldest?

## 10b) Make a graph of the distribution of ages.

> **TIP:** You use `.plot()` to graph values in a column independently, but `.hist()` to draw a [histogram](https://www.mathsisfun.com/data/histograms.html) of the distribution of their values

## 11) Make a scatterplot of net worth compared to age

It's more fun to do this in Altair as compared to matplotlib, but either is fine.

## 13) Make a bar graph of the wealth of the top 10 richest billionaires

> **TIP:** When you make your plot, you'll need to set the `x` and `y` or else your chart will look _crazy_
>
> **TIP:** x and y might be the opposite of what you expect them to be